### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [SebastienPeillet/PisteCreator#4]
Please explain plugin usefulness and remove .pyc files they are generated on install

**Comment by SebastienPeillet** [comment]
The plugin could be usefull for road planning. Especially in rain forest, but also in other environment, the tracks durability depend on slopes. If it's too steep, water wiff runoff and degrade tracks.
The plugin helps the planning operator to find the best path for a track, providing slopes informations when he creates it on Qgis.
Of course, a line layer and a DEM layer are required.

I removed .pyc files and other useless folder created by Plugin Builder.

**Comment by SebastienPeillet** [comment]
Thanks for approval ! 

However I noticed that I forgot one file in my upload on the Qgis plugins Repository. So I deleted the current version and uploaded again the plugin with the missing file.

Any idea about the necessary time to approve this new upoad ? (uploaded the 11th November)

Thanks again !

**Comment by NyakudyaA** [comment]
Hi @SebastienPeillet next time if you have made some mistake you do not need to delete . You just need to make a new version and upload the new version in this case people who have already downloaded your plugin will just get a notification of a new version

**Comment by SebastienPeillet** [comment]
Ok, I'll remember.
I was skeptical about keeping an incomplete version online but indeed I didn't think about notifications.
